version: "3"
services:
  web:
    build: .
    ports:
    - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432
      - TZ=America/Sao_Paulo
    command: >
      sh -c 'yarn && rails db:create db:schema:load && rails s -b 0.0.0.0'
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
    - pg-data:/var/lib/postgresql/data
volumes:
  pg-data: